### ISSUE TITLE
What is the current situation

### ISSUE THREAD

**Issue by lxf1992521** [afbjorklund/gexec#1]
hi，how can i run gexec on rhel6/7 system ? 
the code is too old to compile it ！

-v-

**Comment by afbjorklund** [comment]
Well, the software is old. But it should compile now, even if it might not be ready to run ?
Supposedly it needs a new README, on how to build things... (libe, authd, gexec, pcp)

Here are the old home pages:
http://www.theether.org/authd/
http://www.theether.org/gexec/
http://www.theether.org/pcp/

The old `autogen.sh` scripts don't work anymore, but the individual commands should.
Eventually it should be modernized and support just `autoreconf`, but otherwise it is:

```
    libtoolize -c \
        && autoheader \
        && aclocal \
        && automake --add-missing --foreign \
        && autoconf
```

You forgot to mention your errors.

**Comment by lxf1992521** [comment]
first, thanks very much for yout reply ! i kown the project is too old.
i am a devops who use some tools like ganglia/ansible/puppet/icinga ..., so i want to find a way like gexec to exec remote command and common authentication method by puppet/icinga which using TSL/SSL Cert.

the ganglia-gmond have "gexec = yes" optinons, so i find the http://www.theether.org/gexec/ website, and find your project.

now, i won't use gexec if it is too old, can you recommend some tools like gexec ?
or gexec is still vigorous，and we can use it on RHEL6/7/8...... ?

**Comment by afbjorklund** [comment]
I don't think there's anything wrong with the basic setup, on the contrary - the ganglia concept of "n-ary trees" is a really neat one*. But the current code is using 512-bit RSA keys and SHA-0, so needs update.
- see e.g. "Improving Scalability and Fault Tolerance in an Application Management Infrastructure"
  http://sysnet.cs.williams.edu/~jeannie/papers/plushm-lasco08.pdf

But I haven't yet been in contact with the original author (Brent Chun) or with the Ganglia project, who is currently "maintaining" the code even if it is not in the current repository but only in the old SVN repository:
- `git-svn-id: svn://svn.code.sf.net/p/ganglia/code/trunk/gexec@1397 ac29f823-ce8d-4061-994e-a24588a419ca` 
  https://sourceforge.net/p/ganglia/code/HEAD/tree/trunk/gexec/
